### ISSUE TITLE
Typos and missing content

### ISSUE THREAD

**Issue by delaneyj** [sportx-bet/sportx-js#9]
1. https://sportx-bet.github.io/slate/?shell#get-active-markets  types are false and undefined.  Talking with @mrwillis at least betGroup is always a string
2. https://sportx-bet.github.io/slate/?shell#popular-markets is missing from API
3. https://app.api.sportx.bet/leagues/active is missing from API
4. `getSports()` endpoint missing in Docs
5. https://app.api.sportx.bet/live-scores missing from API

Market API missing
1. liveEnabled 
2. mainLine
3. group1
4. group2

Market Docs missing
1. reportedDate
1. outcome
1. teamOneScore
1. teamTwoScore
1. teamOneMeta
1. teamTwoMeta
1. marketMeta
2. sportID

I just realized Market is really `Market` and `ReportedMarket extends Market`  but in general this area needs cleanup and verification.

1, League API missing `active`

**Comment by mrwillis** [comment]
Closed by https://github.com/sportx-bet/sportx-js/pull/10
